---
title: "Интерактивные карта"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    self_contained: no
---

```{r Интерактивная картограмма, results = 'asis', message = F, cashe = T}
# пакет с API для WorldBank
#install.packages('WDI')
library('WDI')
library('googleVis')
library('leaflet')

# загрузка данных по всем странам, 2016 год, показатель
# GDP (current US$)
dat <- WDI(indicator = 'NY.GDP.MKTP.CD',
start = 2016,
end = 2016)
dat <- dat[, c(2, 3)]
#удаляем значения по миру и тп
dat <- dat[c(48:264),]
dat <- dat[!is.na(dat[,2]),]
# объект: таблица исходных данных
g.tbl <- gvisTable(data = dat, 
                   options = list(width = 220, height = 400))
# объект: интерактивная карта
g.chart <- gvisGeoChart(data = dat, 
                        locationvar = 'country', 
                        colorvar = 'NY.GDP.MKTP.CD', 
                        options = list(width = 500, 
                                       height = 400, 
                                       dataMode = 'regions'))
# размещаем таблицу и карту на одной панели (слева направо)
TG <- gvisMerge(g.tbl, g.chart, 
                horizontal = TRUE, 
                tableOptions = 'bgcolor=\"#CCCCCC\" cellspacing=10')

# вставляем результат в html-документ
print(TG, 'chart')

```

```{r Карта на основе leaflet, results = 'asis', message = F, cashe = T}
#Лого
fileURL <- 'http://nwmos.ru/upload/iblock/e3e/sized_macdonalds_300_new.jpg'
ranepa.icon <- makeIcon(iconUrl = fileURL, 
                        iconWidth = 30,
                        iconHeight = 30)

lat <- c(55.720266222756166,55.71809898912291,55.70002554500563,55.68086917219587,55.69172846686777)
lng <- c(37.82192836789441, 37.78509663114422, 37.855799631767844, 37.88806113284404, 37.89673530982508)
address_ru <- c("Москва, Вешняковская ул., 22А", "Москва, Рязанский просп., 32, стр. 2", "Москва, Лермонтовский просп., 19, корп. 2", "Люберцы, Октябрьский просп., 142", "Люберцы, ул. Побратимов, 7")

df <- data.frame(lat,lng,address_ru)
RANEPA.loc <- df 


# подписи к объектам
ranepa.sites <- paste0("<em>", 
                       df[, 'address_ru'], "</em>")

# создаём виджет с картой
myMap <- RANEPA.loc %>% leaflet(width = 800, height = 800) %>% 
addTiles() %>% addMarkers(icon = ranepa.icon, popup = ranepa.sites)

# рисуем карту
myMap
```